# Importing Libraries and Data

In [1]:
import pandas as pd
import numpy as np
import os

In [144]:
# file path
path = r'/Users/Evan/Desktop/MLB Team Stats Project'

In [38]:
# imoporting data
df = pd.read_csv(os.path.join(path, 'Data', 'Raw Data','mlb_teams_5.csv'))

In [39]:
# data check
df.shape

(2252, 41)

In [40]:
# data check
df.columns

Index(['year', 'league_id', 'division_id', 'rank', 'games_played',
       'home_games', 'wins', 'losses', 'division_winner', 'wild_card_winner',
       'league_winner', 'world_series_winner', 'runs_scored', 'at_bats',
       'hits', 'doubles', 'triples', 'homeruns', 'walks',
       'strikeouts_by_batters', 'stolen_bases', 'caught_stealing',
       'batters_hit_by_pitch', 'sacrifice_flies', 'opponents_runs_scored',
       'earned_runs_allowed', 'earned_run_average', 'complete_games',
       'shutouts', 'saves', 'outs_pitches', 'hits_allowed', 'homeruns_allowed',
       'walks_allowed', 'strikeouts_by_pitchers', 'errors', 'double_plays',
       'fielding_percentage', 'team_name', 'ball_park', 'home_attendance'],
      dtype='object')

# Removing unneeded columns

In [56]:
# dropping columns
df = df.drop(columns = ['home_games', 'home_attendance', 'ball_park', 'outs_pitches'])

In [58]:
# data check
df.shape

(2252, 37)

In [41]:
# data check
df.head(50)

,year,league_id,division_id,rank,games_played,home_games,wins,losses,division_winner,wild_card_winner,...,hits_allowed,homeruns_allowed,walks_allowed,strikeouts_by_pitchers,errors,double_plays,fielding_percentage,team_name,ball_park,home_attendance
0,1920,AL,NaN,5,154,76,72,81,NaN,NaN,...,1481,39,461,481,183,131,0.972,Boston Red Sox,Fenway Park I,402445
1,1920,NL,NaN,1,155,78,93,61,NaN,NaN,...,1381,25,327,553,226,118,0.966,Brooklyn Robins,Ebbets Field,808722
2,1920,NL,NaN,7,153,74,62,90,NaN,NaN,...,1464,39,415,368,239,125,0.964,Boston Braves,Braves Field,162483
3,1920,AL,NaN,2,154,77,96,58,NaN,NaN,...,1467,45,405,438,194,142,0.969,Chicago White Sox,Comiskey Park,833492
4,1920,NL,NaN,5,154,77,75,79,NaN,NaN,...,1459,37,382,508,225,112,0.965,Chicago Cubs,Wrigley Field,480783
5,1920,NL,NaN,3,154,77,82,71,NaN,NaN,...,1327,26,393,435,200,125,0.968,Cincinnati Reds,Crosley Field,568107
6,1920,AL,NaN,1,154,78,98,56,NaN,NaN,...,1448,31,401,466,185,124,0.971,Cleveland Indians,League Park II,912832
7,1920,AL,NaN,7,155,78,61,93,NaN,NaN,...,1487,46,561,483,229,95,0.965,Detroit Tigers,Navin Field,579650
8,1920,NL,NaN,2,155,80,86,68,NaN,NaN,...,1379,44,297,380,209,137,0.969,New York Giants,Polo Grounds IV,929609
9,1920,AL,NaN,3,154,77,95,59,NaN,NaN,...,1414,48,420,480,193,129,0.970,New York Yankees,Polo Grounds IV,1289422
10,1920,AL,NaN,8,156,77,48,106,NaN,NaN,...,1612,56,461,423,267,126,0.959,Philadelphia Athletics,Shibe Park,287888
11,1920,NL,NaN,8,153,77,62,91,NaN,NaN,...,1480,35,444,419,232,135,0.964,Philadelphia Phillies,Baker Bowl,330998
12,1920,NL,NaN,4,155,78,79,75,NaN,NaN,...,1389,25,280,444,186,119,0.971,Pittsburgh Pirates,Forbes Field,429037
13,1920,AL,NaN,4,154,78,76,77,NaN,NaN,...,1481,53,578,444,231,119,0.963,St. Louis Browns,Sportsman's Park IV,419311
14,1920,NL,NaN,5,155,76,75,79,NaN,NaN,...,1488,30,479,529,256,136,0.961,St. Louis Cardinals,Robison Field/Sportsman's Park IV,326836
15,1920,AL,NaN,6,153,76,68,84,NaN,NaN,...,1521,51,520,418,232,95,0.963,Washington Senators,Griffith Stadium I,359260
16,1921,AL,NaN,5,154,77,75,79,NaN,NaN,...,1521,53,452,446,157,151,0.975,Boston Red Sox,Fenway Park I,279273
17,1921,NL,NaN,5,152,78,77,75,NaN,NaN,...,1556,46,361,471,232,142,0.964,Brooklyn Robins,Ebbets Field,613245
18,1921,NL,NaN,4,153,74,79,74,NaN,NaN,...,1488,54,420,382,199,122,0.969,Boston Braves,Braves Field,318627
19,1921,AL,NaN,7,154,77,62,92,NaN,NaN,...,1603,52,549,392,199,155,0.969,Chicago White Sox,Comiskey Park,543650
20,1921,NL,NaN,7,153,76,64,89,NaN,NaN,...,1605,67,409,441,166,129,0.974,Chicago Cubs,Wrigley Field,410107
21,1921,NL,NaN,6,153,76,70,83,NaN,NaN,...,1500,37,305,408,193,139,0.969,Cincinnati Reds,Crosley Field,311227
22,1921,AL,NaN,2,154,77,94,60,NaN,NaN,...,1534,43,431,475,204,124,0.967,Cleveland Indians,League Park II,748705
23,1921,AL,NaN,6,154,77,71,82,NaN,NaN,...,1634,71,495,452,231,107,0.964,Detroit Tigers,Navin Field,661527
24,1921,NL,NaN,1,153,79,94,59,NaN,NaN,...,1497,79,295,357,187,155,0.971,New York Giants,Polo Grounds IV,973477
25,1921,AL,NaN,1,153,78,98,55,NaN,NaN,...,1461,51,470,481,220,138,0.965,New York Yankees,Polo Grounds IV,1230696
26,1921,AL,NaN,8,155,77,53,100,NaN,NaN,...,1645,85,548,431,277,144,0.957,Philadelphia Athletics,Shibe Park,344430
27,1921,NL,NaN,8,154,76,51,103,NaN,NaN,...,1665,79,371,333,294,127,0.955,Philadelphia Phillies,Baker Bowl,273961
28,1921,NL,NaN,2,154,76,90,63,NaN,NaN,...,1448,37,322,500,171,129,0.973,Pittsburgh Pirates,Forbes Field,701567
29,1921,AL,NaN,3,154,77,81,73,NaN,NaN,...,1541,71,556,477,224,127,0.964,St. Louis Browns,Sportsman's Park IV,355978
30,1921,NL,NaN,3,154,78,87,66,NaN,NaN,...,1486,61,399,464,219,130,0.965,St. Louis Cardinals,Sportsman's Park IV,384773
31,1921,AL,NaN,4,154,76,80,73,NaN,NaN,...,1568,51,442,452,234,153,0.963,Washington Senators,Griffith Stadium I,456069
32,1922,AL,NaN,8,154,73,61,93,NaN,NaN,...,1508,48,503,359,221,139,0.965,Boston Red Sox,Fenway Park I,259184
33,1922,NL,NaN,6,155,78,76,78,NaN,NaN,...,1574,74,490,499,208,139,0.967,Brooklyn Robins,Ebbets Field,498865
34,1922,NL,NaN,8,154,76,53,100,NaN,NaN,...,1565,57,489,360,215,121,0.965,Boston Braves,Braves Field,167965
35,1922,AL,NaN,5,155,77,77,77,NaN,NaN,...,1472,57,529,484,153,132,0.976,Chicago White Sox,Comiskey Park,602860
36,1922,NL,NaN,5,156,76,80,74,NaN,NaN,...,1579,77,475,402,202,154,0.968,Chicago Cubs,Wrigley Field,542283
37,1922,NL,NaN,2,156,79,86,68,NaN,NaN,...,1481,49,326,357,205,147,0.968,Cincinnati Reds,Crosley Field,493754
38,1922,AL,NaN,4,155,80,78,76,NaN,NaN,...,1605,58,464,489,201,140,0.968,Cleveland Indians,League Park II,528145
39,1922,AL,NaN,3,155,77,79,75,NaN,NaN,...,1554,62,473,461,192,135,0.970,Detroit Tigers,Navin Field,861206
40,1922,NL,NaN,1,156,79,93,61,NaN,NaN,...,1454,71,393,388,194,145,0.970,New York Giants,Polo Grounds IV,945809
41,1922,AL,NaN,1,154,77,94,60,NaN,NaN,...,1402,73,423,458,155,122,0.975,New York Yankees,Polo Grounds IV,1026134
42,1922,AL,NaN,7,155,78,65,89,NaN,NaN,...,1573,107,469,373,218,119,0.965,Philadelphia Athletics,Shibe Park,425356
43,1922,NL,NaN,7,154,77,57,96,NaN,NaN,...,1692,89,460,394,222,152,0.966,Philadelphia Phillies,Baker Bowl,232471
44,1922,NL,NaN,3,155,78,85,69,NaN,NaN,...,1613,52,358,490,187,126,0.970,Pittsburgh Pirates,Forbes Field,523675
45,1922,AL,NaN,2,154,77,93,61,NaN,NaN,...,1412,71,419,534,196,158,0.968,St. Louis Browns,Sportsman's Park IV,712918
46,1922,NL,NaN,3,154,77,85,69,NaN,NaN,...,1609,61,447,465,239,122,0.961,St. Louis Cardinals,Sportsman's Park IV,536998
47,1922,AL,NaN,6,154,79,69,85,NaN,NaN,...,1485,49,500,422,201,161,0.968,Washington Senators,Griffith Stadium I,458552
48,1923,AL,NaN,8,154,78,61,91,NaN,NaN,...,1534,48,520,412,232,126,0.963,Boston Red Sox,Fenway Park I,229688
49,1923,NL,NaN,6,155,78,76,78,NaN,NaN,...,1503,55,476,548,291,137,0.955,Brooklyn Robins,Ebbets Field,564666

In [37]:
# data types and info check
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2784 entries, 0 to 2783
Data columns (total 41 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   year                    2784 non-null   int64
 1   league_id               2784 non-null   object
 2   division_id             1438 non-null   object
 3   rank                    2784 non-null   int64
 4   games_played            2784 non-null   int64
 5   home_games              2556 non-null   float64
 6   wins                    2784 non-null   int64
 7   losses                  2784 non-null   int64
 8   division_winner         1410 non-null   object
 9   wild_card_winner        774 non-null    object
 10  league_winner           2756 non-null   object
 11  world_series_winner     2536 non-null   object
 12  runs_scored             2784 non-null   int64
 13  at_bats                 2784 non-null   int64
 14  hits                    2784 non-null   int64
 15  doubles                 2784 non-null   int64
 16  triples                 2784 non-null   int64
 17  homeruns                2784 non-null   int64
 18  walks                   2784 non-null   int64
 19  strikeouts_by_batters   2768 non-null   float64
 20  stolen_bases            2708 non-null   float64
 21  caught_stealing         2076 non-null   float64
 22  batters_hit_by_pitch    1718 non-null   float64
 23  sacrifice_flies         1414 non-null   float64
 24  opponents_runs_scored   2784 non-null   int64
 25  earned_runs_allowed     2784 non-null   int64
 26  earned_run_average      2784 non-null   float64
 27  complete_games          2784 non-null   int64
 28  shutouts                2784 non-null   int64
 29  saves                   2784 non-null   int64
 30  outs_pitches            2784 non-null   int64
 31  hits_allowed            2784 non-null   int64
 32  homeruns_allowed        2784 non-null   int64
 33  walks_allowed           2784 non-null   int64
 34  strikeouts_by_pitchers  2784 non-null   int64
 35  errors                  2784 non-null   int64
 36  double_plays            2784 non-null   int64
 37  fielding_percentage     2784 non-null   float64
 38  team_name               2784 non-null   object
 39  ball_park               2784 non-null   object
 40  home_attendance         2676 non-null   float64
dtypes: float64(9), int64(24), object(8)
memory usage: 891.9+ KB

# Adding Geographic columns to satisfy requirement

In [136]:
# Assigning state
def state(row):
    if row ['team_name'] == ('Anaheim Angels'):
        return 'California'
    elif row ['team_name'] == ('Oakland Athletics'):
        return 'California'
    elif row ['team_name'] == ('San Francisco Giants'):
        return 'California'
    elif row ['team_name'] == ('San Diego Padres'):
        return 'California'
    elif row ['team_name'] == ('California Angels'):
        return 'California'
    elif row ['team_name'] == ('Los Angeles Angels'):
        return 'California'
    elif row ['team_name'] == ('Los Angeles Angels of Anaheim'):
        return 'California'
    elif row ['team_name'] == ('Los Angeles Dodgers'):
        return 'California'
    elif row ['team_name'] == ('Brooklyn Dodgers'):
        return 'New York'
    elif row ['team_name'] == ('New York Yankees'):
        return 'New York'
    elif row ['team_name'] == ('New York Mets'):
        return 'New York'
    elif row ['team_name'] == ('New York Giants'):
        return 'New York'
    elif row ['team_name'] == ('Brooklyn Robins'):
        return 'New York'
    elif row ['team_name'] == ('Houston Astros'):
        return 'Texas'
    elif row ['team_name'] == ('Texas Rangers'):
        return 'Texas'
    elif row ['team_name'] == ('Boston Red Sox'):
        return 'Massachusetts'
    elif row ['team_name'] == ('Boston Bees'):
        return 'Massachusetts'
    elif row ['team_name'] == ('Boston Braves'):
        return 'Massachusetts'
    elif row ['team_name'] == ('Arizona Diamondbacks'):
        return 'Arizona'
    elif row ['team_name'] == ('Atlanta Braves'):
        return 'Georgia'
    elif row ['team_name'] == ('Baltimore Orioles'):
        return 'Maryland'
    elif row ['team_name'] == ('Chicago Cubs' or 'Chicago White Sox'):
        return 'Illinois'
    elif row ['team_name'] == ('Chicago White Sox'):
        return 'Illinois'
    elif row ['team_name'] == ('Cincinnati Redlegs'):
        return 'Ohio'
    elif row ['team_name'] == ('Cincinnati Reds'):
        return 'Ohio'
    elif row ['team_name'] == ('Cleveland Indians'):
        return 'Ohio'
    elif row ['team_name'] == ('Florida Marlins'):
        return 'Florida'
    elif row ['team_name'] == ('Miami Marlins'):
        return 'Florida'
    elif row ['team_name'] == ('Tampa Bay Devil Rays'):
        return 'Florida'
    elif row ['team_name'] == ('Tampa Bay Rays'):
        return 'Florida'
    elif row ['team_name'] == ('Colorado Rockies'):
        return 'Colorado'
    elif row ['team_name'] == ('Detroit Tigers'):
        return 'Michigan'
    elif row ['team_name'] == ('St. Louis Cardinals'):
        return 'Missouri'
    elif row ['team_name'] == ('St.Louis Browns'):
        return 'Missouri'
    elif row ['team_name'] == ('Kansas City Royals'):
        return 'Missouri'
    elif row ['team_name'] == ('Kansas City Athletics'):
        return 'Missouri'
    elif row ['team_name'] == ('Milwaukee Brewers' or 'Milwaukee Braves'):
        return 'Wisconsin'
    elif row ['team_name'] == ('Milwaukee Braves'):
        return 'Wisconsin'
    elif row ['team_name'] == ('Philadelphia Phillies'):
        return 'Pennsylvania'
    elif row ['team_name'] == ('Philadelphia Athletics'):
        return 'Pennsylvania'
    elif row ['team_name'] == ('Pittsburgh Pirates'):
        return 'Pennsylvania'
    elif row ['team_name'] == ('Philadelphia Blue Jays'):
        return 'Pennsylvania'
    elif row ['team_name'] == ('Minnesota Twins'):
        return 'Minnesota'
    elif row ['team_name'] == ('Toronto Blue Jays'):
        return 'Ontario'
    elif row ['team_name'] == ('Montreal Expos'):
        return 'Quebec'
    elif row ['team_name'] == ('Seattle Mariners' or 'Seattle Pilots'):
        return 'Washington'
    elif row ['team_name'] == ('Seattle Pilots'):
        return 'Washington'
    elif row ['team_name'] == ('Washington Senators' or 'Washington Nationals'):
        return 'Washington DC'
    elif row ['team_name'] == ('Washington Nationals'):
        return 'Washington DC'
    else: return 'Texas'

In [137]:
df['state'] = df.apply(state, axis = 1)

In [138]:
df.tail(50)

,year,league_id,division_id,rank,games_played,wins,losses,division_winner,wild_card_winner,league_winner,...,saves,hits_allowed,homeruns_allowed,walks_allowed,strikeouts_by_pitchers,errors,double_plays,fielding_percentage,team_name,state
2202,2019,AL,W,1,162,107,55,Y,N,Y,...,47,1205,230,448,1671,71,96,0.988,Houston Astros,Texas
2203,2019,AL,C,4,162,59,103,N,N,N,...,37,1525,221,582,1230,73,152,0.988,Kansas City Royals,Missouri
2204,2019,AL,W,4,162,72,90,N,N,N,...,32,1417,267,576,1404,92,118,0.984,Los Angeles Angels of Anaheim,California
2205,2019,NL,W,1,162,106,56,Y,N,N,...,44,1201,185,392,1519,106,117,0.982,Los Angeles Dodgers,California
2206,2019,NL,E,5,162,57,105,N,N,N,...,27,1340,236,615,1378,94,135,0.984,Miami Marlins,Florida
2207,2019,NL,C,2,162,89,73,N,Y,N,...,50,1364,225,570,1497,97,135,0.983,Milwaukee Brewers,Wisconsin
2208,2019,AL,C,1,162,101,61,Y,N,N,...,50,1456,198,452,1463,111,130,0.981,Minnesota Twins,Minnesota
2209,2019,AL,E,1,162,103,59,Y,N,N,...,50,1374,248,507,1534,102,135,0.982,New York Yankees,New York
2210,2019,NL,E,3,162,86,76,N,N,N,...,38,1405,204,500,1520,99,129,0.983,New York Mets,New York
2211,2019,AL,W,2,162,97,65,N,Y,N,...,45,1342,201,477,1299,80,122,0.987,Oakland Athletics,California
2212,2019,NL,E,4,162,81,81,N,N,N,...,36,1452,258,546,1392,97,136,0.984,Philadelphia Phillies,Pennsylvania
2213,2019,NL,C,5,162,69,93,N,N,N,...,31,1511,241,584,1443,121,130,0.980,Pittsburgh Pirates,Pennsylvania
2214,2019,NL,W,5,162,70,92,N,N,N,...,47,1394,215,463,1475,116,100,0.980,San Diego Padres,California
2215,2019,AL,W,5,162,68,94,N,N,N,...,34,1484,260,505,1239,132,145,0.978,Seattle Mariners,Washington
2216,2019,NL,W,3,162,77,85,N,N,N,...,41,1395,227,519,1368,90,142,0.985,San Francisco Giants,California
2217,2019,NL,C,1,162,91,71,Y,N,N,...,52,1284,191,545,1399,66,168,0.989,St. Louis Cardinals,Missouri
2218,2019,AL,E,2,162,96,66,N,Y,N,...,46,1274,181,453,1621,87,126,0.985,Tampa Bay Rays,Florida
2219,2019,AL,W,3,162,78,84,N,N,N,...,33,1515,241,583,1379,105,143,0.982,Texas Rangers,Texas
2220,2019,AL,E,4,162,67,95,N,N,N,...,33,1450,228,604,1332,96,141,0.984,Toronto Blue Jays,Ontario
2221,2019,NL,E,2,162,93,69,N,Y,Y,...,40,1340,202,517,1511,87,111,0.985,Washington Nationals,Washington DC
2222,2020,NL,W,5,60,25,35,N,N,N,...,13,506,93,235,524,35,54,0.983,Arizona Diamondbacks,Arizona
2223,2020,NL,E,1,60,35,25,Y,N,N,...,13,494,69,220,506,33,52,0.985,Atlanta Braves,Georgia
2224,2020,AL,E,4,60,25,35,N,N,N,...,11,489,79,192,487,43,42,0.980,Baltimore Orioles,Maryland
2225,2020,AL,E,5,60,24,36,N,N,N,...,14,587,98,252,537,45,59,0.979,Boston Red Sox,Massachusetts
2226,2020,AL,C,2,60,35,25,N,Y,N,...,13,448,71,217,523,38,48,0.982,Chicago White Sox,Illinois
2227,2020,NL,C,1,60,34,26,Y,N,N,...,16,451,74,182,523,30,46,0.986,Chicago Cubs,Illinois
2228,2020,NL,C,2,60,31,29,N,Y,N,...,9,401,67,213,615,27,36,0.986,Cincinnati Reds,Ohio
2229,2020,AL,C,2,60,35,25,N,Y,N,...,20,440,68,157,621,30,46,0.986,Cleveland Indians,Ohio
2230,2020,NL,W,4,60,26,34,N,N,N,...,16,579,83,205,393,42,78,0.981,Colorado Rockies,Colorado
2231,2020,AL,C,5,58,23,35,N,N,N,...,11,511,91,192,444,27,46,0.987,Detroit Tigers,Michigan
2232,2020,AL,W,2,60,29,31,N,Y,N,...,16,472,70,217,526,20,48,0.991,Houston Astros,Texas
2233,2020,AL,C,4,60,26,34,N,N,N,...,19,500,76,211,517,31,62,0.985,Kansas City Royals,Missouri
2234,2020,AL,W,4,60,26,34,N,N,N,...,12,492,82,199,523,36,36,0.983,Los Angeles Angels of Anaheim,California
2235,2020,NL,W,1,60,43,17,Y,N,Y,...,15,424,66,145,517,40,46,0.982,Los Angeles Dodgers,California
2236,2020,NL,E,2,60,31,29,N,Y,N,...,18,506,82,226,451,39,60,0.981,Miami Marlins,Florida
2237,2020,NL,C,4,60,29,31,N,Y,N,...,14,446,67,189,614,34,45,0.984,Milwaukee Brewers,Wisconsin
2238,2020,AL,C,1,60,36,24,Y,N,N,...,17,448,62,170,535,20,39,0.990,Minnesota Twins,Minnesota
2239,2020,AL,E,2,60,33,27,N,Y,N,...,14,455,83,168,528,48,37,0.976,New York Yankees,New York
2240,2020,NL,E,4,60,26,34,N,N,N,...,11,511,81,219,574,32,39,0.985,New York Mets,New York
2241,2020,AL,W,1,60,36,24,Y,N,N,...,17,471,69,165,506,26,33,0.987,Oakland Athletics,California
2242,2020,NL,E,3,60,28,32,N,N,N,...,11,550,80,185,532,35,57,0.983,Philadelphia Phillies,Pennsylvania
2243,2020,NL,C,5,60,19,41,N,N,N,...,6,451,80,249,536,47,53,0.978,Pittsburgh Pirates,Pennsylvania
2244,2020,NL,W,2,60,37,23,N,Y,N,...,13,456,70,170,565,32,46,0.985,San Diego Padres,California
2245,2020,AL,W,3,60,27,33,N,N,N,...,15,482,79,230,469,23,48,0.989,Seattle Mariners,Washington
2246,2020,NL,W,3,60,29,31,N,N,N,...,13,474,69,210,488,41,43,0.980,San Francisco Giants,California
2247,2020,NL,C,3,58,30,28,N,Y,N,...,13,376,69,204,464,33,46,0.983,St. Louis Cardinals,Missouri
2248,2020,AL,E,1,60,40,20,Y,N,Y,...,23,475,70,168,552,33,52,0.985,Tampa Bay Rays,Florida
2249,2020,AL,W,5,60,22,38,N,N,N,...,10,479,81,236,489,40,40,0.981,Texas Rangers,Texas
2250,2020,AL,E,3,60,32,28,N,Y,N,...,17,517,81,250,519,38,47,0.982,Toronto Blue Jays,Ontario
2251,2020,NL,E,4,60,26,34,N,N,N,...,12,548,94,216,508,39,48,0.981,Washington Nationals,Washington DC

In [140]:
# Assigning cities
def city(row):
    if row ['team_name'] == ('Anaheim Angels'):
        return 'Anaheim'
    elif row ['team_name'] == ('Oakland Athletics'):
        return 'Oakland'
    elif row ['team_name'] == ('San Francisco Giants'):
        return 'San Francisco'
    elif row ['team_name'] == ('San Diego Padres'):
        return 'San Diego'
    elif row ['team_name'] == ('California Angels'):
        return 'Anaheim'
    elif row ['team_name'] == ('Los Angeles Angels'):
        return 'Anaheim'
    elif row ['team_name'] == ('Los Angeles Angels of Anaheim'):
        return 'Anaheim'
    elif row ['team_name'] == ('Los Angeles Dodgers'):
        return 'Los Angeles'
    elif row ['team_name'] == ('Brooklyn Dodgers'):
        return 'New York'
    elif row ['team_name'] == ('New York Yankees'):
        return 'New York'
    elif row ['team_name'] == ('New York Mets'):
        return 'New York'
    elif row ['team_name'] == ('New York Giants'):
        return 'New York'
    elif row ['team_name'] == ('Brooklyn Robins'):
        return 'New York'
    elif row ['team_name'] == ('Houston Astros'):
        return 'Houston'
    elif row ['team_name'] == ('Texas Rangers'):
        return 'Arlington'
    elif row ['team_name'] == ('Boston Red Sox'):
        return 'Boston'
    elif row ['team_name'] == ('Boston Bees'):
        return 'Boston'
    elif row ['team_name'] == ('Boston Braves'):
        return 'Boston'
    elif row ['team_name'] == ('Arizona Diamondbacks'):
        return 'Phoenix'
    elif row ['team_name'] == ('Atlanta Braves'):
        return 'Atlanta'
    elif row ['team_name'] == ('Baltimore Orioles'):
        return 'Baltimore'
    elif row ['team_name'] == ('Chicago Cubs'):
        return 'Chicago'
    elif row ['team_name'] == ('Chicago White Sox'):
        return 'Chicago'
    elif row ['team_name'] == ('Cincinnati Redlegs'):
        return 'Cincinnati'
    elif row ['team_name'] == ('Cincinnati Reds'):
        return 'Cincinnati'
    elif row ['team_name'] == ('Cleveland Indians'):
        return 'Cleveland'
    elif row ['team_name'] == ('Florida Marlins'):
        return 'Miami'
    elif row ['team_name'] == ('Miami Marlins'):
        return 'Miami'
    elif row ['team_name'] == ('Tampa Bay Devil Rays'):
        return 'Tampa'
    elif row ['team_name'] == ('Tampa Bay Rays'):
        return 'Tampa'
    elif row ['team_name'] == ('Colorado Rockies'):
        return 'Denver'
    elif row ['team_name'] == ('Detroit Tigers'):
        return 'Detroit'
    elif row ['team_name'] == ('St. Louis Cardinals'):
        return 'St. Louis'
    elif row ['team_name'] == ('St.Louis Browns'):
        return 'St. Louis'
    elif row ['team_name'] == ('Kansas City Royals'):
        return 'Kansas City'
    elif row ['team_name'] == ('Kansas City Athletics'):
        return 'Kansas City'
    elif row ['team_name'] == ('Milwaukee Brewers' or 'Milwaukee Braves'):
        return 'Milwaukee'
    elif row ['team_name'] == ('Milwaukee Braves'):
        return 'Milwaukee'
    elif row ['team_name'] == ('Philadelphia Phillies'):
        return 'Philadelphia'
    elif row ['team_name'] == ('Philadelphia Athletics'):
        return 'Philadelphia'
    elif row ['team_name'] == ('Pittsburgh Pirates'):
        return 'Pittsburgh'
    elif row ['team_name'] == ('Philadelphia Blue Jays'):
        return 'Philadelphia'
    elif row ['team_name'] == ('Minnesota Twins'):
        return 'Minneapolis'
    elif row ['team_name'] == ('Toronto Blue Jays'):
        return 'Toronto'
    elif row ['team_name'] == ('Montreal Expos'):
        return 'Montreal'
    elif row ['team_name'] == ('Seattle Mariners'):
        return 'Seattle'
    elif row ['team_name'] == ('Seattle Pilots'):
        return 'Seattle'
    elif row ['team_name'] == ('Washington Senators' or 'Washington Nationals'):
        return 'Washington DC'
    elif row ['team_name'] == ('Washington Nationals'):
        return 'Washington DC'
    else: return 'Houston'

In [141]:
df['city'] = df.apply(city, axis = 1)

In [142]:
df.tail(50)

,year,league_id,division_id,rank,games_played,wins,losses,division_winner,wild_card_winner,league_winner,...,hits_allowed,homeruns_allowed,walks_allowed,strikeouts_by_pitchers,errors,double_plays,fielding_percentage,team_name,state,city
2202,2019,AL,W,1,162,107,55,Y,N,Y,...,1205,230,448,1671,71,96,0.988,Houston Astros,Texas,Houston
2203,2019,AL,C,4,162,59,103,N,N,N,...,1525,221,582,1230,73,152,0.988,Kansas City Royals,Missouri,Kansas City
2204,2019,AL,W,4,162,72,90,N,N,N,...,1417,267,576,1404,92,118,0.984,Los Angeles Angels of Anaheim,California,Anaheim
2205,2019,NL,W,1,162,106,56,Y,N,N,...,1201,185,392,1519,106,117,0.982,Los Angeles Dodgers,California,Los Angeles
2206,2019,NL,E,5,162,57,105,N,N,N,...,1340,236,615,1378,94,135,0.984,Miami Marlins,Florida,Miami
2207,2019,NL,C,2,162,89,73,N,Y,N,...,1364,225,570,1497,97,135,0.983,Milwaukee Brewers,Wisconsin,Milwaukee
2208,2019,AL,C,1,162,101,61,Y,N,N,...,1456,198,452,1463,111,130,0.981,Minnesota Twins,Minnesota,Minneapolis
2209,2019,AL,E,1,162,103,59,Y,N,N,...,1374,248,507,1534,102,135,0.982,New York Yankees,New York,New York
2210,2019,NL,E,3,162,86,76,N,N,N,...,1405,204,500,1520,99,129,0.983,New York Mets,New York,New York
2211,2019,AL,W,2,162,97,65,N,Y,N,...,1342,201,477,1299,80,122,0.987,Oakland Athletics,California,Oakland
2212,2019,NL,E,4,162,81,81,N,N,N,...,1452,258,546,1392,97,136,0.984,Philadelphia Phillies,Pennsylvania,Philadelphia
2213,2019,NL,C,5,162,69,93,N,N,N,...,1511,241,584,1443,121,130,0.980,Pittsburgh Pirates,Pennsylvania,Pittsburgh
2214,2019,NL,W,5,162,70,92,N,N,N,...,1394,215,463,1475,116,100,0.980,San Diego Padres,California,San Diego
2215,2019,AL,W,5,162,68,94,N,N,N,...,1484,260,505,1239,132,145,0.978,Seattle Mariners,Washington,Seattle
2216,2019,NL,W,3,162,77,85,N,N,N,...,1395,227,519,1368,90,142,0.985,San Francisco Giants,California,San Francisco
2217,2019,NL,C,1,162,91,71,Y,N,N,...,1284,191,545,1399,66,168,0.989,St. Louis Cardinals,Missouri,St. Louis
2218,2019,AL,E,2,162,96,66,N,Y,N,...,1274,181,453,1621,87,126,0.985,Tampa Bay Rays,Florida,Tampa
2219,2019,AL,W,3,162,78,84,N,N,N,...,1515,241,583,1379,105,143,0.982,Texas Rangers,Texas,Arlington
2220,2019,AL,E,4,162,67,95,N,N,N,...,1450,228,604,1332,96,141,0.984,Toronto Blue Jays,Ontario,Toronto
2221,2019,NL,E,2,162,93,69,N,Y,Y,...,1340,202,517,1511,87,111,0.985,Washington Nationals,Washington DC,Washington DC
2222,2020,NL,W,5,60,25,35,N,N,N,...,506,93,235,524,35,54,0.983,Arizona Diamondbacks,Arizona,Phoenix
2223,2020,NL,E,1,60,35,25,Y,N,N,...,494,69,220,506,33,52,0.985,Atlanta Braves,Georgia,Atlanta
2224,2020,AL,E,4,60,25,35,N,N,N,...,489,79,192,487,43,42,0.980,Baltimore Orioles,Maryland,Baltimore
2225,2020,AL,E,5,60,24,36,N,N,N,...,587,98,252,537,45,59,0.979,Boston Red Sox,Massachusetts,Boston
2226,2020,AL,C,2,60,35,25,N,Y,N,...,448,71,217,523,38,48,0.982,Chicago White Sox,Illinois,Chicago
2227,2020,NL,C,1,60,34,26,Y,N,N,...,451,74,182,523,30,46,0.986,Chicago Cubs,Illinois,Chicago
2228,2020,NL,C,2,60,31,29,N,Y,N,...,401,67,213,615,27,36,0.986,Cincinnati Reds,Ohio,Cincinnati
2229,2020,AL,C,2,60,35,25,N,Y,N,...,440,68,157,621,30,46,0.986,Cleveland Indians,Ohio,Cleveland
2230,2020,NL,W,4,60,26,34,N,N,N,...,579,83,205,393,42,78,0.981,Colorado Rockies,Colorado,Denver
2231,2020,AL,C,5,58,23,35,N,N,N,...,511,91,192,444,27,46,0.987,Detroit Tigers,Michigan,Detroit
2232,2020,AL,W,2,60,29,31,N,Y,N,...,472,70,217,526,20,48,0.991,Houston Astros,Texas,Houston
2233,2020,AL,C,4,60,26,34,N,N,N,...,500,76,211,517,31,62,0.985,Kansas City Royals,Missouri,Kansas City
2234,2020,AL,W,4,60,26,34,N,N,N,...,492,82,199,523,36,36,0.983,Los Angeles Angels of Anaheim,California,Anaheim
2235,2020,NL,W,1,60,43,17,Y,N,Y,...,424,66,145,517,40,46,0.982,Los Angeles Dodgers,California,Los Angeles
2236,2020,NL,E,2,60,31,29,N,Y,N,...,506,82,226,451,39,60,0.981,Miami Marlins,Florida,Miami
2237,2020,NL,C,4,60,29,31,N,Y,N,...,446,67,189,614,34,45,0.984,Milwaukee Brewers,Wisconsin,Milwaukee
2238,2020,AL,C,1,60,36,24,Y,N,N,...,448,62,170,535,20,39,0.990,Minnesota Twins,Minnesota,Minneapolis
2239,2020,AL,E,2,60,33,27,N,Y,N,...,455,83,168,528,48,37,0.976,New York Yankees,New York,New York
2240,2020,NL,E,4,60,26,34,N,N,N,...,511,81,219,574,32,39,0.985,New York Mets,New York,New York
2241,2020,AL,W,1,60,36,24,Y,N,N,...,471,69,165,506,26,33,0.987,Oakland Athletics,California,Oakland
2242,2020,NL,E,3,60,28,32,N,N,N,...,550,80,185,532,35,57,0.983,Philadelphia Phillies,Pennsylvania,Philadelphia
2243,2020,NL,C,5,60,19,41,N,N,N,...,451,80,249,536,47,53,0.978,Pittsburgh Pirates,Pennsylvania,Pittsburgh
2244,2020,NL,W,2,60,37,23,N,Y,N,...,456,70,170,565,32,46,0.985,San Diego Padres,California,San Diego
2245,2020,AL,W,3,60,27,33,N,N,N,...,482,79,230,469,23,48,0.989,Seattle Mariners,Washington,Seattle
2246,2020,NL,W,3,60,29,31,N,N,N,...,474,69,210,488,41,43,0.980,San Francisco Giants,California,San Francisco
2247,2020,NL,C,3,58,30,28,N,Y,N,...,376,69,204,464,33,46,0.983,St. Louis Cardinals,Missouri,St. Louis
2248,2020,AL,E,1,60,40,20,Y,N,Y,...,475,70,168,552,33,52,0.985,Tampa Bay Rays,Florida,Tampa
2249,2020,AL,W,5,60,22,38,N,N,N,...,479,81,236,489,40,40,0.981,Texas Rangers,Texas,Arlington
2250,2020,AL,E,3,60,32,28,N,Y,N,...,517,81,250,519,38,47,0.982,Toronto Blue Jays,Ontario,Toronto
2251,2020,NL,E,4,60,26,34,N,N,N,...,548,94,216,508,39,48,0.981,Washington Nationals,Washington DC,Washington DC

# Basic stats for understanding

In [49]:
# mean, min, and max htis by team
df.groupby('team_name').agg({'hits': ['mean', 'min', 'max']})

                                      hits
                                      mean   min   max
team_name
Anaheim Angels                 1520.625000  1404  1603
Arizona Diamondbacks           1382.782609   482  1566
Atlanta Braves                 1379.690909   556  1608
Baltimore Orioles              1376.358209   523  1614
Boston Bees                    1357.400000  1265  1450
Boston Braves                  1400.785714  1213  1567
Boston Red Sox                 1449.089109   552  1684
Brooklyn Dodgers               1435.692308  1315  1538
Brooklyn Robins                1496.333333  1314  1654
California Angels              1349.000000   944  1571
Chicago Cubs                   1401.336634   422  1722
Chicago White Sox              1400.782178   534  1615
Cincinnati Redlegs             1409.666667  1359  1452
Cincinnati Reds                1393.957895   390  1599
Cleveland Indians              1428.683168   446  1715
Colorado Rockies               1472.964286   528  1664
Detroit Tigers                 1429.316832   463  1724
Florida Marlins                1405.000000  1043  1504
Houston Astros                 1372.375000   478  1581
Houston Colt .45's             1256.000000  1184  1370
Kansas City Athletics          1326.769231  1244  1467
Kansas City Royals             1423.788462   485  1644
Los Angeles Angels             1345.750000  1297  1378
Los Angeles Angels of Anaheim  1386.812500   501  1604
Los Angeles Dodgers            1376.857143   523  1552
Miami Marlins                  1273.444444   472  1497
Milwaukee Braves               1403.615385  1345  1522
Milwaukee Brewers              1381.294118   429  1599
Minnesota Twins                1431.433333   468  1633
Montreal Expos                 1357.805556   883  1482
New York Giants                1462.263158  1268  1769
New York Mets                  1339.237288   551  1553
New York Yankees               1444.524752   473  1683
Oakland Athletics              1355.283019   430  1545
Philadelphia Athletics         1419.571429  1219  1659
Philadelphia Blue Jays         1326.000000  1321  1331
Philadelphia Phillies          1389.535354   500  1783
Pittsburgh Pirates             1427.851485   425  1698
San Diego Padres               1330.307692   506  1521
San Francisco Giants           1373.063492   532  1552
Seattle Mariners               1391.909091   435  1637
Seattle Pilots                 1276.000000  1276  1276
St. Louis Browns               1430.735294  1238  1693
St. Louis Cardinals            1451.465347   410  1732
Tampa Bay Devil Rays           1457.000000  1395  1531
Tampa Bay Rays                 1306.692308   470  1443
Texas Rangers                  1427.673469   420  1653
Toronto Blue Jays              1401.500000   516  1591
Washington Nationals           1346.562500   519  1477
Washington Senators            1394.442308  1205  1620

In [48]:
# mean, min, and max wins by team
df.groupby('team_name').agg({'wins': ['mean', 'min', 'max']})

                                    wins
                                    mean min  max
team_name
Anaheim Angels                 83.000000  70   99
Arizona Diamondbacks           77.739130  25  100
Atlanta Braves                 81.236364  35  106
Baltimore Orioles              79.567164  25  109
Boston Bees                    71.000000  63   79
Boston Braves                  67.500000  38   91
Boston Red Sox                 79.980198  24  108
Brooklyn Dodgers               85.269231  62  105
Brooklyn Robins                77.500000  65   93
California Angels              76.250000  47   93
Chicago Cubs                   76.792079  34  103
Chicago White Sox              76.990099  35   99
Cincinnati Redlegs             78.333333  74   91
Cincinnati Reds                78.526316  31  108
Cleveland Indians              79.930693  35  111
Colorado Rockies               73.535714  26   92
Detroit Tigers                 78.178218  23  104
Florida Marlins                75.526316  51   92
Houston Astros                 79.178571  29  107
Houston Colt .45's             65.333333  64   66
Kansas City Athletics          63.769231  52   74
Kansas City Royals             75.519231  26  102
Los Angeles Angels             77.000000  70   86
Los Angeles Angels of Anaheim  82.687500  26  100
Los Angeles Dodgers            85.603175  43  106
Miami Marlins                  65.111111  31   79
Milwaukee Braves               88.153846  83   95
Milwaukee Brewers              76.039216  29   96
Minnesota Twins                78.600000  36  102
Montreal Expos                 76.527778  52   95
New York Giants                82.657895  55   98
New York Mets                  75.830508  26  108
New York Yankees               90.990099  33  114
Oakland Athletics              82.056604  36  104
Philadelphia Athletics         69.771429  48  107
Philadelphia Blue Jays         62.500000  61   64
Philadelphia Phillies          71.959596  28  102
Pittsburgh Pirates             77.455446  19   98
San Diego Padres               72.769231  37   98
San Francisco Giants           81.380952  29  103
Seattle Mariners               73.772727  27  116
Seattle Pilots                 64.000000  64   64
St. Louis Browns               66.647059  43   93
St. Louis Cardinals            84.514851  30  106
Tampa Bay Devil Rays           64.500000  55   70
Tampa Bay Rays                 83.153846  40   97
Texas Rangers                  77.183673  22   96
Toronto Blue Jays              77.613636  32   99
Washington Nationals           78.000000  26   98
Washington Senators            71.692308  50   99

In [47]:
# mean, min, and max wins by year
df.groupby('year').agg({'wins': ['mean', 'min', 'max']})

           wins
           mean min  max
year
1920  76.750000  48   98
1921  76.625000  51   98
1922  76.937500  53   94
1923  76.625000  50   98
1924  76.500000  53   93
...         ...  ..  ...
2016  80.900000  59  103
2017  81.000000  64  104
2018  81.033333  47  108
2019  80.966667  47  107
2020  29.933333  19   43

[101 rows x 3 columns]

In [46]:
# mean, min, and max stolen bases by team
df.groupby('team_name').agg({'stolen_bases': ['mean', 'min', 'max']})

                              stolen_bases
                                      mean  min  max
team_name
Anaheim Angels                  111.000000   71  143
Arizona Diamondbacks             88.391304   23  137
Atlanta Braves                   86.090909   23  165
Baltimore Orioles                75.820896   19  150
Boston Bees                      41.200000   23   49
Boston Braves                    59.714286   20  100
Boston Red Sox                   64.019802   18  126
Brooklyn Dodgers                 72.038462   36  117
Brooklyn Robins                  68.583333   34  106
California Angels                90.750000   40  220
Chicago Cubs                     74.198020   22  182
Chicago White Sox                94.138614   19  191
Cincinnati Redlegs               53.333333   45   65
Cincinnati Reds                  97.968421   19  210
Cleveland Indians                79.653465   19  160
Colorado Rockies                 98.250000   42  201
Detroit Tigers                   72.861386   17  176
Florida Marlins                 108.578947   65  177
Houston Astros                  119.071429   22  198
Houston Colt .45's               40.333333   39   42
Kansas City Athletics            58.307692   16  132
Kansas City Royals              125.480769   49  218
Los Angeles Angels               43.750000   37   49
Los Angeles Angels of Anaheim   106.062500   21  161
Los Angeles Dodgers             109.650794   29  198
Miami Marlins                    78.888889   45  149
Milwaukee Braves                 50.846154   26   75
Milwaukee Brewers               102.568627   15  256
Minnesota Twins                  84.433333   14  151
Montreal Expos                  126.777778   51  237
New York Giants                  55.552632   19  137
New York Mets                    93.406780   20  200
New York Yankees                 78.772277   24  163
Oakland Athletics               111.547170   26  341
Philadelphia Athletics           51.400000   25   98
Philadelphia Blue Jays           30.500000   29   32
Philadelphia Phillies            79.838384   25  186
Pittsburgh Pirates               84.831683   16  260
San Diego Padres                106.769231   36  239
San Francisco Giants             88.285714   19  148
Seattle Mariners                103.886364   48  174
Seattle Pilots                  167.000000  167  167
St. Louis Browns                 59.441176   17  132
St. Louis Cardinals              96.188119   17  314
Tampa Bay Devil Rays            119.000000   73  151
Tampa Bay Rays                  110.615385   48  194
Texas Rangers                    98.795918   46  196
Toronto Blue Jays                96.022727   28  193
Washington Nationals             90.937500   33  123
Washington Senators              74.346154   13  161

In [50]:
# mean, min, and max ERA by team
df.groupby('team_name').agg({'earned_run_average': ['mean', 'min', 'max']})

                              earned_run_average
                                            mean   min   max
team_name
Anaheim Angels                          4.406250  3.69  5.00
Arizona Diamondbacks                    4.240435  3.66  5.09
Atlanta Braves                          3.823091  2.92  4.85
Baltimore Orioles                       4.038507  2.53  5.59
Boston Bees                             3.726000  3.22  4.36
Boston Braves                           4.002143  2.96  5.12
Boston Red Sox                          4.153960  3.33  5.58
Brooklyn Dodgers                        3.822308  2.84  4.68
Brooklyn Robins                         3.811667  2.62  4.92
California Angels                       3.858750  3.06  5.42
Chicago Cubs                            3.959010  2.93  5.27
Chicago White Sox                       4.016931  2.45  5.41
Cincinnati Redlegs                      4.160000  3.73  4.62
Cincinnati Reds                         3.898421  2.82  5.19
Cleveland Indians                       4.011584  2.66  5.28
Colorado Rockies                        4.998929  4.14  6.01
Detroit Tigers                          4.192079  2.71  6.38
Florida Marlins                         4.336316  3.83  5.18
Houston Astros                          3.828929  2.66  5.42
Houston Colt .45's                      3.560000  3.41  3.83
Kansas City Athletics                   4.378462  3.56  5.35
Kansas City Royals                      4.236731  3.21  5.65
Los Angeles Angels                      3.610000  2.91  4.31
Los Angeles Angels of Anaheim           4.163125  3.57  5.12
Los Angeles Dodgers                     3.450476  2.62  4.47
Miami Marlins                           4.314444  3.71  4.86
Milwaukee Braves                        3.529231  3.11  4.12
Milwaukee Brewers                       4.177255  3.38  5.14
Minnesota Twins                         4.163333  2.84  5.76
Montreal Expos                          3.819722  3.08  5.13
New York Giants                         3.734211  2.71  4.61
New York Mets                           3.812034  2.72  5.04
New York Yankees                        3.763069  2.79  4.88
Oakland Athletics                       3.947925  2.58  5.48
Philadelphia Athletics                  4.401143  3.00  6.08
Philadelphia Blue Jays                  3.715000  3.64  3.79
Philadelphia Phillies                   4.204747  3.02  6.71
Pittsburgh Pirates                      3.920990  2.74  5.24
San Diego Padres                        3.969038  3.22  4.98
San Francisco Giants                    3.800635  2.71  4.86
Seattle Mariners                        4.357500  3.17  5.24
Seattle Pilots                          4.350000  4.35  4.35
St. Louis Browns                        4.629118  3.14  6.24
St. Louis Cardinals                     3.741584  2.49  5.14
Tampa Bay Devil Rays                    5.012000  4.35  5.53
Tampa Bay Rays                          3.758462  3.19  4.33
Texas Rangers                           4.391224  3.31  5.71
Toronto Blue Jays                       4.249545  3.31  5.14
Washington Nationals                    4.075625  3.03  5.09
Washington Senators                     4.112308  2.92  5.33

In [51]:
# mean, min, and max ERA by year
df.groupby('year').agg({'earned_run_average': ['mean', 'min', 'max']})

     earned_run_average
                   mean   min   max
year
1920           3.461875  2.62  4.17
1921           4.031250  3.17  4.94
1922           4.066875  3.38  4.64
1923           3.988750  3.21  5.34
1924           4.050000  3.12  4.87
...                 ...   ...   ...
2016           4.184333  3.15  5.09
2017           4.352667  3.30  5.36
2018           4.148000  3.11  5.18
2019           4.497000  3.37  5.59
2020           4.447667  3.02  5.63

[101 rows x 3 columns]

In [53]:
# mean, min, and max HR by team
df.groupby('team_name').agg({'homeruns': ['mean', 'min', 'max']})

                                 homeruns
                                     mean  min  max
team_name
Anaheim Angels                 165.500000  147  236
Arizona Diamondbacks           167.434783   58  220
Atlanta Braves                 151.800000   64  249
Baltimore Orioles              157.537313   52  257
Boston Bees                     59.800000   54   67
Boston Braves                   63.464286   16  148
Boston Red Sox                 131.821782   17  245
Brooklyn Dodgers               106.153846   33  208
Brooklyn Robins                 64.833333   28  122
California Angels              122.250000   55  192
Chicago Cubs                   127.950495   34  256
Chicago White Sox              112.099010   22  242
Cincinnati Redlegs             170.000000  123  221
Cincinnati Reds                120.989474   18  227
Cleveland Indians              127.792079   26  223
Colorado Rockies               179.035714   63  239
Detroit Tigers                 133.970297   30  225
Florida Marlins                148.210526   94  208
Houston Astros                 130.303571   45  288
Houston Colt .45's              79.000000   62  105
Kansas City Athletics          113.846154   69  166
Kansas City Royals             121.884615   61  193
Los Angeles Angels             130.750000   95  189
Los Angeles Angels of Anaheim  163.375000   85  220
Los Angeles Dodgers            137.190476   67  279
Miami Marlins                  125.555556   60  194
Milwaukee Braves               171.538462  139  199
Milwaukee Brewers              152.647059   75  250
Minnesota Twins                139.383333   47  307
Montreal Expos                 121.694444   81  178
New York Giants                121.131579   46  221
New York Mets                  131.474576   57  242
New York Yankees               157.811881   93  306
Oakland Athletics              158.415094   71  257
Philadelphia Athletics          85.685714   26  172
Philadelphia Blue Jays          60.500000   55   66
Philadelphia Phillies          121.020202   40  224
Pittsburgh Pirates             106.039604   16  171
San Diego Padres               124.807692   32  219
San Francisco Giants           142.650794   63  235
Seattle Mariners               156.227273   60  264
Seattle Pilots                 125.000000  125  125
St. Louis Browns                80.000000   46  118
St. Louis Cardinals            112.287129   32  235
Tampa Bay Devil Rays           148.800000  111  190
Tampa Bay Rays                 171.230769   80  228
Texas Rangers                  162.979592   49  260
Toronto Blue Jays              168.409091   61  257
Washington Nationals           160.625000   66  231
Washington Senators             74.057692   22  163

In [59]:
# mean, min, and max HR by year
df.groupby('year').agg({'homeruns': ['mean', 'min', 'max']})

        homeruns
            mean  min  max
year
1920   39.375000   16  115
1921   58.562500   17  134
1922   65.937500   32  116
1923   61.250000   26  112
1924   56.000000   22   98
...          ...  ...  ...
2016  187.000000  122  253
2017  203.500000  128  241
2018  186.166667  128  267
2019  225.866667  146  307
2020   76.800000   51  118

[101 rows x 3 columns]

In [145]:
df.to_pickle(os.path.join(path, 'Data', 'Prepared Data', 'mlb_teams_clean.pkl'))